# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-23 23:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Deptford', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unitinformation',
            old_name='name',
            new_name='construction_ref',
        ),
        migrations.RemoveField(
            model_name='unitinformation',
            name='building',
        ),
    ]
